// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32YZ0D1tuJiAYdCF26_EPbJGkNvARt48',
    appId: '1:983310396129:web:f03df303a7131b589fe5a0',
    messagingSenderId: '983310396129',
    projectId: 'chat-app-c61f6',
    authDomain: 'chat-app-c61f6.firebaseapp.com',
    storageBucket: 'chat-app-c61f6.firebasestorage.app',
    measurementId: 'G-Y7C68TXMLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_fFtkwIVTcJ8k33kzpcKk02ygJBuFORg',
    appId: '1:983310396129:android:40d2d7659d449ef39fe5a0',
    messagingSenderId: '983310396129',
    projectId: 'chat-app-c61f6',
    storageBucket: 'chat-app-c61f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBisHA5vyEWSvVrZd6sFojvJYdYg0B06pY',
    appId: '1:983310396129:ios:47504aee9f09921d9fe5a0',
    messagingSenderId: '983310396129',
    projectId: 'chat-app-c61f6',
    storageBucket: 'chat-app-c61f6.firebasestorage.app',
    iosBundleId: 'com.example.vibeChat',
  );
}
